<?php
/** @var \OmniPro\JaimeSantana\Block\Template $block */
?>

<div class="back-v">
    <img src="<?= $block->getViewFileUrl('OmniPro_JaimeSantana::images/back-v.svg') ?>">
</div>

<div class="back-a">
    <img src="<?= $block->getViewFileUrl('OmniPro_JaimeSantana::images/back-a.svg') ?>">
</div>


<div class="back-c">
    <img src="<?= $block->getViewFileUrl('OmniPro_JaimeSantana::images/back-c.svg') ?>">
</div>