<?php

/** @var \OmniPro\JaimeSantana\Block\Template $block */
?>

<div class="login-success">
    <img src="<?= $block->getViewFileUrl('OmniPro_JaimeSantana::images/success-icon.svg') ?>">
</div>

<div class="tabBox">

    <div class="tabBox__tab">
        <button class="tabBox__tablinks" onclick="openTab(event, 'form-login')" id="defaultOpen">INGRESO</button>
        <button class="tabBox__tablinks" onclick="openTab(event, 'form-register')" id="btnRegister">REGISTRO</button>
    </div>

    <div id="form-login" class="tabBox__tabcontent">
        <form onsubmit="return success()" action="https://app.prueba-magento.test/default/beaumont-summit-kit.html">
            <label for="login-email">EMAIL</label>
            <input type="email" id="login-email" required>
            <label for="login-password">CONTRASEÑA</label>
            <input type="password" id="login-password" required>
            <div class="tabBox__news">

                <label class="tabBox__switch" id="switch">
                    <input type="checkbox" class="tabBox__form-checkbox">
                    <span class="tabBox__slider round"></span>
                </label>
                <label for="switch" class="tabBox__switch-label">Subscribirse al Newsletter</label>
            </div>
            <button type="submit">Ingreso</button>
            <div class="tabBox__forgotPass">
                <a href="">Olvide contraseña</a>
            </div>
        </form>
    </div>

    <div id="form-register" class="tabBox__tabcontent">
        <form onsubmit="return success()">
            <label for="firstname">NOMBRE</label>
            <input type="text" id="firstname" required>
            <label for="lastname">APELLIDO</label>
            <input type="text" id="lastname" required>
            <label for="email-register">EMAIL</label>
            <input type="email" id="email-register" required>
            <label for="password-register">CONTRASEÑA</label>
            <input type="password" id="password-register" required>
            <button type="submit">Registro</button>
        </form>
    </div>
</div>