<?php

/** @var \OmniPro\JaimeSantana\Block\Template $block */
?>

<div class="login-success">
    <img src="<?= $block->getViewFileUrl('OmniPro_JaimeSantana::images/menubar.svg') ?>">
</div>

<div class="tabBox">

    <div class="tab">
        <button class="tablinks" onclick="openTab(event, 'form-login')" id="defaultOpen">Login</button>
        <button class="tablinks" onclick="openTab(event, 'form-register')" id="btnRegister">Register</button>
    </div>

    <div id="form-login" class="tabcontent">
        <form onsubmit="return false">
            <label for="login-email">EMAIL</label>
            <input type="email" id="login-email" placeholder="example@email.com" required>
            <label for="login-password">CONTRASEÑA</label>
            <input type="password" id="login-password" placeholder="******" required>
            <div class="news">

                <label class="switch" id="switch">
                    <input type="checkbox" class="form-checkbox">
                    <span class="slider round"></span>
                </label>
                <label for="switch">Subscribirse al Newsletter</label>
            </div>
            <button type="submit" action="" onclick="success()">Ingreso</button>
            <div class="forgotPass">
                <a href="">Olvide contraseña</a>
            </div>
        </form>
    </div>

    <div id="form-register" class="tabcontent">
        <form>
            <label for="firstname">NOMBRE</label>
            <input type="text" id="firstname" required>
            <label for="lastname">APELLIDO</label>
            <input type="text" id="lastname" required>
            <label for="email-register">EMAIL</label>
            <input type="email" id="email-register" required>
            <label for="password-register">CONTRASEÑA</label>
            <input type="password" id="password-register" required>
            <button type="submit">Registro</button>
        </form>
    </div>
</div>