<?php

/** @var \OmniPro\JaimeSantana\Block\Template $block */
?>

<nav>
    <ul>
        <li>Inicio</li>
        <li>Servicios</li>
        <li>Nuestro Equipo</li>
        <li>Portafolio</li>
        <li>Contácto</li>
        <li>Términos y Condiciones</li>
    </ul>
</nav>

<div class="form-login">
    <form>
        <label for="email-login">EMAIL</label>
        <input type="email" id="email-login">
        <label for="password-login">CONTRASEÑA</label>
        <input type="password" id="password-login">
        <input type="checkbox" id="subscribe">
        <label for="subscribe">Subscribirse al Newsletter</label>
        <br>
        <button type="submit">Ingreso</button>
        <button type="submit">Olvide contraseña</button>
    </form>
</div>

<div>
    <form>
        <label for="firstname">NOMBRE</label>
        <input type="text" id="firstname">
        <label for="lastname">APELLIDO</label>
        <input type="text" id="lastname">
        <label for="email-register">EMAIL</label>
        <input type="email" id="email-register">
        <label for="password-register">CONTRASEÑA</label>
        <input type="password" id="password-register">
        <button type="submit">Registro</button>
    </form>
</div>