<?php

/** @var \OmniPro\JaimeSantana\Block\Template $block */
?>

<nav>
    <ul>
        <li>Inicio</li>
        <li>Servicios</li>
        <li>Nuestro Equipo</li>
        <li>Portafolio</li>
        <li>Contácto</li>
        <li>Términos y Condiciones</li>
    </ul>
</nav>

<div class="tabBox">

    <div class="tab">
        <button class="tablinks" onclick="openTab(event, 'form-login')" id="defaultOpen">Login</button>
        <button class="tablinks" onclick="openTab(event, 'form-register')">Register</button>
    </div>

    <div id="form-login" class="tabcontent">
        <form>
            <label for="email-login">EMAIL</label>
            <input type="email" id="email-login" placeholder="example@email.com">
            <label for="password-login">CONTRASEÑA</label>
            <input type="password" id="password-login" placeholder="******">
            <div class="news">

                <label class="switch" id="switch">
                    <input type="checkbox">
                    <span class="slider round"></span>
                </label>
                <label for="switch">Subscribirse al Newsletter</label>
            </div>
            <br>
            <button type="submit">Ingreso</button>
            <button type="submit">Olvide contraseña</button>
        </form>
    </div>

    <div id="form-register" class="tabcontent">
        <form>
            <label for="firstname">NOMBRE</label>
            <input type="text" id="firstname">
            <label for="lastname">APELLIDO</label>
            <input type="text" id="lastname">
            <label for="email-register">EMAIL</label>
            <input type="email" id="email-register">
            <label for="password-register">CONTRASEÑA</label>
            <input type="password" id="password-register">
            <button type="submit">Registro</button>
        </form>
    </div>
</div>