<?php

/** @var \OmniPro\JaimeSantana\Block\Template $block */
?>

<nav class="navbar">

    <input type="checkbox" id="check" class="checkbox">
    <label for="check" class="checklabel">
        <img src="<?= $block->getViewFileUrl('OmniPro_JaimeSantana::images/menubar.svg') ?>" alt="menu">
    </label>

    <ul class="nav-ul">
        <li class="nav-li"><a href="#">Inicio</a></li>
        <li class="nav-li"><a href="#">Servicios</a></li>
        <li class="nav-li"><a href="#">Nuestro equipo</a></li>
        <li class="nav-li"><a href="#">Portafolio</a></li>
        <li class="nav-li"><a href="#">Contacto</a></li>
        <li class="nav-li"><a href="#">Términos y condiciones</a></li>
    </ul>

</nav>